Name = "dup"
Owner = "rytmrt"
Version = "0.1.0"
Description = "Do updating by difference in the choose version and the current version"
Framework = "codegangsta_cli"

[[Commands]]
  Name = "deploy"
  Synopsis = "Deploy to diff"
  Help = "[Usage] dup deploy [-nD] [-r choose_rev]"

[[Commands]]
  Name = "init"
  Synopsis = "Create skeleton for deplpyment"
  Help = "[Usage] dup init [-N server_name]"

[[Commands]]
  Name = "list"
  Synopsis = "Show server list"
  Help = "[Usage] dup list"

[[Commands]]
  Name = "add"
  Synopsis = "Add server infomation"
  Help = "[Usage] dup add <server_name> [-h hostname] [-p port] [-l login_name] [-i identity_file]"

[[Commands]]
  Name = "chg"
  Synopsis = "Change server infomation"
  Help = "[Usage] dup chg <server_name> [-h hostname] [-p port] [-l login_name] [-i identity_file]"

[[Commands]]
  Name = "del"
  Synopsis = "Change server infomation"
  Help = "[Usage] dup del <server_name>"
