Name = "dup"
Owner = "Ryota Morita"
Version = "0.1.0"
Description = "Do updating by difference in the choose version and the current version"
Framework = "codegangsta_cli"

[[Commands]]
  Name = "deploy"
  Synopsis = "Deploy to diff"
  Help = "[Usage] dup deploy [-nD] [-r choose_rev]"

[[Commands]]
  Name = "init"
  Synopsis = "Create skeleton for deplpyment"
  Help = "[Usage] dup init [-N server_name]"

[[Commands]]
  Name = "server-list"
  Synopsis = "Show server list"
  Help = "[Usage] dup server-list"

[[Commands]]
  Name = "server-add"
  Synopsis = "Add server infomation"
  Help = "[Usage] dup server-add <server_name> [-h hostname] [-p port] [-l login_name] [-i identity_file]"

[[Commands]]
  Name = "server-chg"
  Synopsis = "Change server infomation"
  Help = "[Usage] dup server-chg <server_name> [-h hostname] [-p port] [-l login_name] [-i identity_file]"

[[Commands]]
  Name = "server-del"
  Synopsis = "Change server infomation"
  Help = "[Usage] dup server-del <server_name>"
